### ISSUE TITLE
Problem with first segment of a camelCase variable

### ISSUE THREAD

**Issue by fuadsaud** [Julian/vim-textobj-variable-segment#13] opened 2015-03-17 17:36 UTC
I'm having the following situation on a project:

https://asciinema.org/a/17791

I'm running vim 4.7.488. Not sure what's going wrong.

**Comment by Julian** [comment] 2015-03-17 22:19
This is a dupe of #11 -- it's definitely an issue, I know it's broken, I just haven't been able to fight with vim's regex engine hard enough to figure out how to fix it. Would love a patch if you see the problem.

**Closed by Julian** 2015-03-17 22:19 UTC

**Comment by fuadsaud** [comment] 2015-03-17 22:45
Right. I don't know much Vimscript but if the problem is it related to the regex it might be worth trying.

**Comment by Julian** [comment] 2015-03-17 22:53
Yeah :/ it is, but it's vim's nuances in prioritizing branches, or something. I'm not sure, it's been awhile since I've looked at it again, so someone just needs to sit there, write the test case, and try to get all of them to pass.
