### ISSUE TITLE
Single-character CamelCase segments seem not to work

### ISSUE THREAD

**Issue by chiphogg** [Julian/vim-textobj-variable-segment#11] opened 2014-03-13 17:39 UTC
Examples:
1. Start with `aBadTime`.  Place cursor on `B`.  Type `civGood<ESC>`.  Result should be `aGoodTime`.  Instead, I get `GoodBadTime`.  (Rather unexpected: the character under the cursor is _not included in the variable segment_!)
2. Start with `AgainABadTime`.  Place cursor on `B` and type the same command.  Result should be `AgainAGoodTime`.  Instead, I get `AgainGoodTime`.  (Looks like two variable segments, `A` and `Bad`, got conflated.)

**Comment by mortenbh** [comment] 2015-05-10 13:55
New user of vim-textobj-variable-segment here! I came to open an issue on this topic, but since it already reported, I will just say that I can confirm this bug. As you might expect, it's especially noticable when working on a C++ codebase, which uses the common convention of prefixing all member variables with 'm', such as 'mMemberVariable'.

**Comment by Julian** [comment] 2015-05-10 14:01
Yeah unfortunately I still haven't been able to figure out vim's regexes to figure out how this should be fixed. Patches welcome if you find the issue :/.

**Closed** 2024-09-06 19:06 UTC

**Comment by chiphogg** [comment] 2024-09-08 18:34
Thank you!  Works like a dream.  :smile:

**Comment by jafinn3** [comment] 2024-09-13 15:07
After this patch, I'm getting

```
Error detected while processing function 7[2]..<SNR>20_select_function_wrapper[3]..textobj#variable_segment#select_a[1]..<SNR>117_select_a[3]..<SNR>117_select[40]..<lambda>25[1]..<SNR>117_closest_position:
line    1:
E117: Unknown function: mapnew
line    2:
E117: Unknown function: mapnew
line    3:
E121: Undefined variable: a_distance
line    6:
E121: Undefined variable: a_distance
line    9:
E121: Undefined variable: a_distance
line   12:
E121: Undefined variable: a_distance
```

What is `mapnew`? I can't find any documentation on that function anywhere. I'm on Neovim, maybe related to the problem:

```
 nvim --version 
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794
```

Would be nice to keep this plugin compatible with Neovim -- it's become so engrained in my workflow I don't know if I can live without it :)

**Comment by Julian** [comment] 2024-09-13 15:13
(I use neovim and have no such issue -- I don't have time to investigate, but 0.9 is EOL, so perhaps try upgrading to 0.10.)

**Comment by jafinn3** [comment] 2024-09-13 18:11
> (I use neovim and have no such issue -- I don't have time to investigate, but 0.9 is EOL, so perhaps try upgrading to 0.10.)

Upgrading fixed it, probably should have tried that first. Thanks
